variable "access_key" {}
variable "secret_key" {}
variable "region" {}
variable "vpc_name" {}
variable "subnet_name" {}
variable "subnet_name_b" {}
variable "vpc_cidr" {}
variable "subnet_cidr" {}
variable "subnet_cidr_b" {}
variable "domain_name" {}
variable "demo_dhcp_opts_name" {}
variable "demo_elb_name" {}
variable "ec2_instance_userdata" {}
variable "ec2_instance_host_name" {}
variable "ec2_instance_instance_type" {}
variable "ec2_instance_root_block_dev_size" {}
variable "ec2_instance_root_block_dev_type" {}
variable "ec2_instance_ami" {}
variable "demo_ssh_key_name" {}
variable "demo_ssh_key_path" {}
variable "r53_zone_id" {}
variable "my_cidr" {}